CREATE SEQUENCE SEQ_ALERTAS
 START WITH 1
 INCREMENT BY 1
 NOCACHE
 NOCYCLE;

CREATE TABLE ALERTAS (
ID_ALERTA INT PRIMARY KET IDENTITY,
SENSOR_ID INT,
TIPO_ALERTA VARCHAR(100),
DATA_HORA DATETIME,
MENSAGEM_ALERTA VARCHAR(255),
FOREIGN KEY (SENSOR_ID) REFERENCES SENSORES(SENSOR_ID)

);