CREATE SEQUENCE ID_SENSOR
 START WITH 1
 INCREMENT BY 1
 NOCACHE
 NOCYCLE;

CREATE TABLE SENSORES(
ID_SENSOR INT PRIMARY KEY IDENTITY,
NOME VARCHAR(100),
TIPO VARCHAR(50),
ID_LOCALIZACAO INT,
FOREIGN KEY (ID_LOCALIZACAO) REFERENCES LOCALIZACOES(ID_LOCALIZACAO)

);